/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaintingsRouteImport } from './routes/paintings'
import { Route as IndexRouteImport } from './routes/index'

const PaintingsRoute = PaintingsRouteImport.update({
  id: '/paintings',
  path: '/paintings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/paintings': typeof PaintingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/paintings': typeof PaintingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/paintings': typeof PaintingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/paintings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/paintings'
  id: '__root__' | '/' | '/paintings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaintingsRoute: typeof PaintingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paintings': {
      id: '/paintings'
      path: '/paintings'
      fullPath: '/paintings'
      preLoaderRoute: typeof PaintingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaintingsRoute: PaintingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
